server:
  port: 8080

spring:
  application:
    name: spring-boot-hazelcast-cache
  datasource:
    url: jdbc:postgresql://localhost:5432/hazelcast_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
