# Application Settings
server.port=8080
spring.application.name=spring-boot-logging

# Logging Levels
logging.level.root=INFO
logging.level.com.haydikodlayalim=DEBUG

# Logging File Configuration
logging.file.name=logs/application.log

# Logging Pattern Formats
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
