spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

sr.rabbit.queue.name=notification-queue
sr.rabbit.exchange.name=notification-exchange
sr.rabbit.routing.name=notification-routing-key

server.port=8081
spring.amqp.deserialization.trust.all=true
